### ISSUE TITLE
Update links for cloud lab resources

### ISSUE THREAD

**Issue by kyleoconnell-NIH** [NIGMS/NIGMS-Sandbox#24]
Update all links here and in child repos to match the new cloud lab format. If it is general cloud content it lives [here](https://scan.cloud.nih.gov/resources/cloudlab/google-cloud-jumpstart/) and if its a tutorial it lives [here](https://github.com/STRIDES/NIHCloudLabGCP), but note that the paths to these has changes slightly such that there is no /tutorials dir anymore.

**Comment by kyleoconnell-NIH** [comment]
@JohnTurnerNIH  are all repos in the org updated?

**Comment by JohnTurnerNIH** [comment]
All the links I could find that related to the org have been updated. There are some other links found by a link checker that I would need to look deeper into.
